# satellite_expansion.py
import os, datetime

BASE_DIR = os.getcwd()  # Current directory as base for new sites
LOG_FILE = "logs/satellite_expansion.log"

def create_blog_site(site_name, description=""):
    """Create a new blog site with the given name and an optional description."""
    site_path = os.path.join(BASE_DIR, site_name)
    os.makedirs(site_path, exist_ok=True)
    os.makedirs(os.path.join(site_path, "posts"), exist_ok=True)
    # Index page
    index_content = f"<html>\n<head><title>{site_name}</title></head>\n<body>\n"
    index_content += f"<h1>Welcome to {site_name}</h1>\n"
    index_content += f"<p>{description or 'This is an auto-generated blog site.'}</p>\n"
    index_content += f"<ul>\n<li><a href='posts/hello.html'>Hello World</a></li>\n</ul>\n"
    index_content += "</body>\n</html>"
    with open(os.path.join(site_path, "index.html"), 'w') as f:
        f.write(index_content)
    # Create a hello world post
    post_content = "<html>\n<head><title>Hello World</title></head>\n<body>\n"
    post_content += "<h2>Hello World</h2>\n<p>This is the first post on the blog. Stay tuned for more content!</p>\n"
    post_content += "</body>\n</html>"
    with open(os.path.join(site_path, "posts", "hello.html"), 'w') as f:
        f.write(post_content)
    # Log the creation
    with open(LOG_FILE, 'a') as logf:
        logf.write(f"{datetime.datetime.now()}: Created new blog site '{site_name}' at {site_path}\n")

def create_podcast_site(site_name, description=""):
    """Create a new podcast site structure with the given name."""
    site_path = os.path.join(BASE_DIR, site_name)
    os.makedirs(site_path, exist_ok=True)
    os.makedirs(os.path.join(site_path, "episodes"), exist_ok=True)
    index_content = f"# {site_name}\n\n{description or 'This is an auto-generated podcast site.'}\n"
    index_content += "\n## Episodes\n- [Episode 1](episodes/episode1.txt)\n"
    with open(os.path.join(site_path, "README.md"), 'w') as f:
        f.write(index_content)
    ep_content = "Episode 1: Introduction\n\nWelcome to our new podcast. This episode is a placeholder for future content."
    with open(os.path.join(site_path, "episodes", "episode1.txt"), 'w') as f:
        f.write(ep_content)
    # Log the creation
    with open(LOG_FILE, 'a') as logf:
        logf.write(f"{datetime.datetime.now()}: Created new podcast site '{site_name}' at {site_path}\n")

# Example usage:
if __name__ == "__main__":
    create_blog_site("AutoCreatorX_Blog", "A blog generated by AutoCreatorX covering various topics.")
    create_podcast_site("AutoCreatorX_Podcast", "A podcast generated by AutoCreatorX (placeholder content).")
    print("New sites created in the current directory.")
